<?php
/**
 * @var Cardpay\Core\Block\CustomTicket\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();
$paymentResponse = $payment->getAdditionalInformation("paymentResponse");
$payment_method = $this->getPaymentMethod();

//generate link to order
$successMsg = 'Your order %1 has been successfully generated.';
$link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>';
?>

<?php
if (!$this->checkExistCallback() && $this->getRedirectUserStatus()) {
    ?>
    <script>
        window.location.href = "<?php echo $paymentResponse['transaction_details']['redirect_url']; ?>";
    </script>
<?php } ?>

<div id="box-cardpay">
    <?php if ($payment_method === 'cardpay_custom_bank_transfer') { ?>

        <?php if (!$this->checkExistCallback()) { ?>
            <h2 class="cardpay-title">
                <?php /* @escapeNotVerified */
                echo __('Thank you for your purchase!'); ?>
            </h2>

            <p>
                <?php /* @escapeNotVerified */
                echo __('Your order %1 has been successfully generated.',
                    '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>');
                ?>
            </p>

            <p>
                <?php /* @escapeNotVerified */
                echo __('The payment will be credited in less than 1 hour.'); ?>
            </p>

            <?php if (isset($paymentResponse['transaction_details']) && $paymentResponse['transaction_details']['redirect_url']) { ?>

                <a href="<?php echo $block->escapeUrl(urldecode($paymentResponse['transaction_details']['redirect_url'])); ?>"
                   id="btn-boleto-cardpay">
                    <?php /* @escapeNotVerified */
                    echo __('Pay'); ?>
                </a>

            <?php } ?>

        <?php } else { ?>

            <?php
            $message_status = $this->getMessageByStatus($paymentResponse);
            if (isset($message_status['title']) && isset($message_status['message'])) {
                ?>
                <h2 class="cardpay-title"><?php echo $block->escapeHtml($message_status['title']); ?></h2>

                <p><?php echo $block->escapeHtml($message_status['message']); ?></p>

            <?php } else { ?>
                <p><?php /* @escapeNotVerified */
                    echo __($successMsg, $link_to_order); ?></p>
            <?php } ?>

            <?php if (isset($message_status['title'], $message_status['message']) && $paymentResponse['status'] !== 'rejected'): ?>
                <p><?php /* @escapeNotVerified */
                    echo __($successMsg, $link_to_order); ?></p>
            <?php endif; ?>

            <h3 class="cardpay-title-info-payment"><?php /* @escapeNotVerified */
                echo __('Payment information'); ?></h3>

            <?php if (isset($paymentResponse['id'])) { ?>
                <p><?php echo __('Payment id (Cardpay): %1', $paymentResponse['id']); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['payment_method_id'])) { ?>
                <p><?php echo __('Payment Method: %1', ucfirst($paymentResponse['payment_method_id'])); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['status'])) { ?>
                <p><?php echo __('Payment Status: %1', ucfirst($paymentResponse['status'])); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['id'])) { ?>
                <p><?php echo __('Payment Status Detail: %1', ucfirst($paymentResponse['status_detail'])); ?></p>
            <?php } ?>
        <?php } ?>

    <?php } else {
        echo __('Error getting the link to the ticket. Please contact the seller.');
    } ?>
</div>

<div id="logo-cardpay">
    <img src="<?php echo $block->getUrl("Cardpay_Core::images/cp_logo.jpg"); ?>" alt="Unlimint"/>
</div>

<div class="primary button-success">
    <?php if ($paymentResponse['status'] === 'rejected'): ?>
        <a class="action primary continue"
           href="<?php echo $block->escapeUrl($block->getReOrderUrl()) ?>"><span><?php /* @escapeNotVerified */
                echo __('Retry order') ?></span></a>
    <?php else: ?>
        <a class="action primary continue"
           href="<?php echo $block->escapeUrl($block->getUrl()) ?>"><span><?php /* @escapeNotVerified */
                echo __('Continue Shopping') ?></span></a>
    <?php endif; ?>
</div>