<?php
/** @var $block \Magento\Checkout\Block\Onepage\Failure */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $scriptString = <<<script
    require([
        'jquery',
        'Magento_Customer/js/customer-data'
    ], function ($, customerData) {
        var sections = ['cart'];
        customerData.reload(sections, true);
    });
script;
?>

<?= /* @noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>

<?php if ($block->getRealOrderId()) : ?>
    <p><?= $block->escapeHtml(__('Order #') . $block->getRealOrderId()) ?></p>
<?php endif ?>

<?php if ($error = $block->getErrorMessage()) : ?>
    <h1><?= $block->escapeHtml($error) ?></h1>
<?php endif ?>

<p><?= $block->escapeHtml(
        __('Click <a href="%1">here</a> to continue shopping.', $block->escapeUrl($block->getContinueShoppingUrl())),
        ['a']
    ) ?>
</p>