<?php
/**
 * @var Cardpay\Core\Block\Custom\Installments $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$installmentsURL = $block->getInstallmentsUrl();
if (empty($installmentsURL)) {
    return;
}

$firstOptionText = __('Select number of installments');

$scriptString = <<<script
    function assignInstallmentOptions() {
        let installmentSelect = document.getElementById('installments');
        if (installmentSelect == null || installmentSelect == 'undefined') {
            return;
        }

        let firstOption = document.createElement('option');
        firstOption.value = '';
        firstOption.text = '$firstOptionText';

        installmentSelect.appendChild(firstOption);

        const xhttp = new XMLHttpRequest();
        xhttp.open('GET', '$installmentsURL', false);
        xhttp.send();
        const ajaxResponse = xhttp.responseText;
        if (ajaxResponse == null || ajaxResponse == 'undefined') {
            for (let n = 1; n <= 12; n++) {
                let option = document.createElement('option');
                option.text = n;
                option.value = n;
                
                installmentSelect.appendChild(option);
            }
            
        } else {
            const responseArray = JSON.parse(ajaxResponse);            
            const currency = responseArray['currency'];
            
            const options = responseArray['options'];
            options.forEach(function (installmentOption) {
                if (installmentOption['installments'] != 'undefined' && installmentOption['amount'] != 'undefined') {
                    const installments = installmentOption['installments'];
                    const amount = installmentOption['amount'];

                    let option = document.createElement('option');
                    option.text = installments + ' x ' + currency + amount;
                    option.value = installments;

                    installmentSelect.appendChild(option);
                }
            })
        }
    }
script;

echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false);