<?php
/**
 * @var Cardpay\Core\Block\Custom\Success $block
 */

$order = $this->getOrder();
$payment = $this->getPayment();

//generate link to order
$successMsg = 'Your order %1 has been successfully generated.';
$link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>';

$paymentResponse = $payment->getAdditionalInformation("paymentResponse");

?>

<div id="box-cardpay">

    <?php if (!isset($paymentResponse['status'])) { ?>

        <h2 class="cardpay-title"><?php /* @escapeNotVerified */
            echo __('Thank you for your purchase!'); ?></h2>
        <p><?php /* @escapeNotVerified */
            echo __($successMsg, $link_to_order); ?></p>

    <?php } else { ?>

        <?php
        $message_status = $this->getMessageByStatus($paymentResponse);
        if (isset($message_status['title']) && isset($message_status['message'])) {
            ?>
            <h2 class="cardpay-title"><?php echo $block->escapeHtml($message_status['title']); ?></h2>

            <p><?php echo $block->escapeHtml($message_status['message']); ?></p>

        <?php } else { ?>
            <p><?php /* @escapeNotVerified */
                echo __($successMsg, $link_to_order); ?></p>
        <?php } ?>

        <?php if ($paymentResponse['status'] != 'rejected' && (isset($message_status['title']) && isset($message_status['message']))): ?>
            <p><?php /* @escapeNotVerified */
                echo __($successMsg, $link_to_order); ?></p>
        <?php endif; ?>

        <h3 class="cardpay-title-info-payment"><?php /* @escapeNotVerified */
            echo __('Payment information'); ?></h3>

        <?php if (isset($paymentResponse['id'])) { ?>
            <p><?php echo __('Payment id (Cardpay): %1', $paymentResponse['id']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['card']) && isset($paymentResponse['card']['first_six_digits']) && isset($paymentResponse['card']['last_four_digits'])) { ?>
            <p><?php echo __('Card Number: %1', $paymentResponse['card']['first_six_digits'] . "xxxxxx" . $paymentResponse['card']['last_four_digits']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['card']) && isset($paymentResponse['card']['expiration_month']) && isset($paymentResponse['card']['expiration_year'])) { ?>
            <p><?php echo __('Expiration Date: %1', $paymentResponse['card']['expiration_month'] . "/" . $paymentResponse['card']['expiration_year']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['card']) && isset($paymentResponse['card']['cardholder']) && isset($paymentResponse['card']['cardholder']['name'])) { ?>
            <p><?php echo __('CardHolder Name: %1', $paymentResponse['card']['cardholder']['name']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['payment_method_id'])) { ?>
            <p><?php echo __('Payment Method: %1', ucfirst($paymentResponse['payment_method_id'])); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['installments'])) { ?>
            <p><?php echo __('Installments: %1', $paymentResponse['installments']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['statement_descriptor'])) { ?>
            <p><?php echo __('Statement Descriptor: %1', $paymentResponse['statement_descriptor']); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['status'])) { ?>
            <p><?php echo __('Payment Status: %1', ucfirst($paymentResponse['status'])); ?></p>
        <?php } ?>

        <?php if (isset($paymentResponse['id'])) { ?>
            <p><?php echo __('Payment Status Detail: %1', ucfirst($paymentResponse['status_detail'])); ?></p>
        <?php } ?>

    <?php } ?>
</div>

<div id="logo-cardpay">
    <img src="<?php echo $block->getUrl("Cardpay_Core::images/cp_logo.jpg"); ?>" alt="Unlimint"/>
</div>

<div class="primary button-success">
    <?php if ($paymentResponse['status'] == 'rejected'): ?>
        <a class="action primary continue"
           href="<?php echo $block->escapeUrl($block->getReOrderUrl()) ?>"><span><?php /* @escapeNotVerified */
                echo __('Retry order') ?></span></a>
    <?php else: ?>
        <a class="action primary continue"
           href="<?php echo $block->escapeUrl($block->getUrl()) ?>"><span><?php /* @escapeNotVerified */
                echo __('Continue Shopping') ?></span></a>
    <?php endif; ?>
</div>
